/* Automatically generated by version.py, do not manually edit! */
#ifndef SUBPROJECTS_FFMPEG_AVUTIL_FFVERSION_H
#define SUBPROJECTS_FFMPEG_AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.2-dev-5947-g7aec52f479"
#endif /* SUBPROJECTS_FFMPEG_AVUTIL_FFVERSION_H */
