/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define BYTEORDER 1234

#define HAVE_FCNTL_H

#define HAVE_INTTYPES_H

#define HAVE_MEMORY_H

#define HAVE_STDINT_H

#define HAVE_STDLIB_H

#define HAVE_STRING_H

#define HAVE_SYS_STAT_H

#define HAVE_SYS_TYPES_H

#define STDC_HEADERS

#define XML_CONTEXT_BYTES 1024

#define XML_DTD

#define XML_NS

