/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define X264_BIT_DEPTH 8

#define X264_CHROMA_FORMAT 0

#define X264_GPL 1

#define X264_INTERLACED 1

#define X264_POINTVER "0.160.3011+52"

#define X264_VERSION " r3011+52 92ea5c1"

